### ISSUE TITLE
Help needed to add more words into the dictionary.

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Hunspell-MS#1]
Adding 450 more words becoming 25000 from 24550 words.

**Comment by RobbiNespu** [comment]
@SyafiqHadzir are you still interested with this project? I would like to contribute but I dont understand where I can start

**Comment by SyafiqHadzir** [comment]
@RobbiNespu , yes I am still interested with this project. However, the project is now stalled/dormant for awhile.
